config: SEGGER_RTT_Conf: remove mutex locking
zephyrproject-rtos/segger pull request #21
Opened 2024-10-04 03:37 UTC by JordanYates

Remove mutex locking in favour of the standard IRQ locking mechanism. The primary problem with the mutex implementation is that mutex locking is forbidden in ISR's. This means that any logging from an interrupt context (e.g. LOG_PANIC in an exception handler), will itself trigger another assertion due its attempt to use a mutex.

Furthermore, mutexes are a relatively heavyweight locking scheme, which doesn't necessarily make sense in the context of extremely short locking periods that would be expected from RTT.

This change aligns Zephyr with the default RTT locking scheme, which uses interrupt masking to perform access control.

Note: not sure where the whitespace diff in Github is coming from, my local tools don't show anything.

2024-10-07 12:31 UTC, henrikbrixandersen requested changes

2024-10-07 12:31 UTC, henrikbrixandersen commented on Config/SEGGER_RTT_Conf.h
There seems to be some unrelated whitespace changes in this commit?

2024-10-07 23:06 UTC, JordanYates commented on Config/SEGGER_RTT_Conf.h
As noted in the PR description, I cannot for the life of me figure out what they are or where they come from.
They don't show up in my local editor and Github isn't being useful.
Normally I would assume newline ending changes, but as far as I can tell that isn't true.

2024-10-07 23:48 UTC, JordanYates commented on Config/SEGGER_RTT_Conf.h
The file apparently previously had a mix of `\r\n` (mostly) and `\n` line endings (the diff that shows) and vscode decided to fix those without showing that there was a difference.

2024-10-08 05:29 UTC, henrikbrixandersen commented on Config/SEGGER_RTT_Conf.h
Okay, that makes sense. We can of course fix that, but in a separate commit.

2024-10-08 05:29 UTC, henrikbrixandersen approved these changes

2024-10-08 06:15 UTC, nordic-krch approved these changes

2024-10-08 06:20 UTC, merged