Update to SystemView v3.58
zephyrproject-rtos/segger pull request #22
Opened 2024-11-29 06:34 UTC by brycewilkins

This repository has suffered a few setbacks over past years with Zephyr related patches being lost (causing things to break for RTT/SystemView/Zephyr), and it has been reported as hard to review PRs due to Windows style line endings. There is also no instruction on how to update from the existing Segger source code to a newer release, leading to partial updates that make subsequent updates more difficult and error prone.

This PR attempts to improve things by:
1. Changing all line endings to Unix style LF (`\n`)
2. Updating (completely) to SystemView v3.58 Target sources 
    - Note: #17 selectively introduced changes from SystemView v3.52a Target sources (many SYSVIEW changes skipped, files still referred to "SystemView version: 3.40", etc.)
4. Adding a README that identifies Segger "upstream" and suggests a procedure for updating to a new Segger release

To do:
- [ ] Testing with SystemView application v3.58
- [ ] Zephyr repo PR

2024-12-07 17:45 UTC, brycewilkins commented
@cfriedt The suggestion for [Unix style line endings](https://github.com/zephyrproject-rtos/segger/pull/17#issuecomment-2479999310) is accommodated in this PR.

@henrikbrixandersen @nordic-krch @nordicjm Hope you are able to have a look.

Thank you!

2024-12-09 06:33 UTC, nordic-krch approved these changes

2024-12-15 16:55 UTC, brycewilkins commented
@cfriedt @henrikbrixandersen Would you be able to have a look? Thank you!

2024-12-16 08:59 UTC, henrikbrixandersen requested changes
Looks good, one small nit.

2024-12-16 08:59 UTC, henrikbrixandersen commented on README.md
Please break the long lines (e.g. at 100 chars) to improve readability.

2024-12-16 14:07 UTC, brycewilkins commented on README.md
Hi @henrikbrixandersen , thanks for the review!

The long URLs create some challenges. What do you recommend as the approach for this:

```
This repository is the Zephyr project module for integrating Segger [RTT](https://www.segger.com/products/debug-probes/j-link/technology/about-real-time-transfer) ([wiki](https://wiki.segger.com/RTT)), [SystemView](https://www.segger.com/products/development-tools/systemview/) ([wiki](https://wiki.segger.com/SystemView)) and [Monitor mode debugging](https://www.segger.com/products/debug-probes/j-link/technology/monitor-mode-debugging/) with Zephyr RTOS.
```

One option:
```
This repository is the Zephyr project module for integrating Segger
[RTT](https://www.segger.com/products/debug-probes/j-link/technology/about-real-time-transfer)
([wiki](https://wiki.segger.com/RTT)),
[SystemView](https://www.segger.com/products/development-tools/systemview/)
([wiki](https://wiki.segger.com/SystemView)) and
[Monitor mode debugging](https://www.segger.com/products/debug-probes/j-link/technology/monitor-mode-debugging/)
with Zephyr RTOS.
```
but that still exceeds 100 chars on one line.

I could move all the URLs to the end of the document in a **References** section.

2024-12-16 14:14 UTC, henrikbrixandersen commented on README.md
Yes, you could convert them to Markdown reference-style links. That would improve readability of the raw file too, I think. 

@kartben Any opinion here?

2024-12-17 05:27 UTC, brycewilkins commented on README.md
@henrikbrixandersen Neater now! 4a239743be04cbeec5c694b5db7c0eac11b75a5b

2024-12-17 07:18 UTC, henrikbrixandersen approved these changes

2024-12-17 07:29 UTC, kartben approved these changes

2024-12-17 07:30 UTC, merged